// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkuRsUfgdZ5gq7uJ_IT7gUfZXBsZzLJuM',
    appId: '1:238065650809:web:2288038c05de5ead5c18a8',
    messagingSenderId: '238065650809',
    projectId: 'neirfriends',
    authDomain: 'neirfriends.firebaseapp.com',
    storageBucket: 'neirfriends.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkuRsUfgdZ5gq7uJ_IT7gUfZXBsZzLJuM',
    appId: '1:238065650809:android:2288038c05de5ead5c18a8',
    messagingSenderId: '238065650809',
    projectId: 'neirfriends',
    storageBucket: 'neirfriends.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkuRsUfgdZ5gq7uJ_IT7gUfZXBsZzLJuM',
    appId: '1:238065650809:ios:2288038c05de5ead5c18a8',
    messagingSenderId: '238065650809',
    projectId: 'neirfriends',
    storageBucket: 'neirfriends.firebasestorage.app',
    iosBundleId: 'com.isimsizacemi.nearfriends',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkuRsUfgdZ5gq7uJ_IT7gUfZXBsZzLJuM',
    appId: '1:238065650809:ios:2288038c05de5ead5c18a8',
    messagingSenderId: '238065650809',
    projectId: 'neirfriends',
    storageBucket: 'neirfriends.firebasestorage.app',
    iosBundleId: 'com.isimsizacemi.nearfriends',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkuRsUfgdZ5gq7uJ_IT7gUfZXBsZzLJuM',
    appId: '1:238065650809:web:2288038c05de5ead5c18a8',
    messagingSenderId: '238065650809',
    projectId: 'neirfriends',
    authDomain: 'neirfriends.firebaseapp.com',
    storageBucket: 'neirfriends.firebasestorage.app',
  );
}
