// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_YtwDOVxsGTodzCABACbH03IBaegdcjs',
    appId: '1:120460073082:web:946b4fbaca78a988a7c3c3',
    messagingSenderId: '120460073082',
    projectId: 'nearfriend-d742f',
    authDomain: 'nearfriend-d742f.firebaseapp.com',
    storageBucket: 'nearfriend-d742f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_YtwDOVxsGTodzCABACbH03IBaegdcjs',
    appId: '1:120460073082:android:946b4fbaca78a988a7c3c3',
    messagingSenderId: '120460073082',
    projectId: 'nearfriend-d742f',
    storageBucket: 'nearfriend-d742f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_YtwDOVxsGTodzCABACbH03IBaegdcjs',
    appId: '1:120460073082:ios:946b4fbaca78a988a7c3c3',
    messagingSenderId: '120460073082',
    projectId: 'nearfriend-d742f',
    storageBucket: 'nearfriend-d742f.firebasestorage.app',
    iosBundleId: 'com.isimsizacemi.nearFriend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_YtwDOVxsGTodzCABACbH03IBaegdcjs',
    appId: '1:120460073082:ios:946b4fbaca78a988a7c3c3',
    messagingSenderId: '120460073082',
    projectId: 'nearfriend-d742f',
    storageBucket: 'nearfriend-d742f.firebasestorage.app',
    iosBundleId: 'com.isimsizacemi.nearFriend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_YtwDOVxsGTodzCABACbH03IBaegdcjs',
    appId: '1:120460073082:web:946b4fbaca78a988a7c3c3',
    messagingSenderId: '120460073082',
    projectId: 'nearfriend-d742f',
    authDomain: 'nearfriend-d742f.firebaseapp.com',
    storageBucket: 'nearfriend-d742f.firebasestorage.app',
  );
}
