const List<String> universityList = [
  'Abdullah Gül Üniversitesi',
  'Acıbadem Mehmet Ali Aydınlar Üniversitesi',
  'Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi',
  'Adıyaman Üniversitesi',
  'Adnan Menderes Üniversitesi',
  'Afyon Kocatepe Üniversitesi',
  'Afyonkarahisar Sağlık Bilimleri Üniversitesi',
  'Ağrı İbrahim Çeçen Üniversitesi',
  'Ahi Evran Üniversitesi',
  'Aksaray Üniversitesi',
  'Alanya Alaaddin Keykubat Üniversitesi',
  'Alanya Hamdullah Emin Paşa Üniversitesi',
  'Altınbaş Üniversitesi',
  'Amasya Üniversitesi',
  'Anadolu Üniversitesi',
  'Ankara Hacı Bayram Veli Üniversitesi',
  'Ankara Medipol Üniversitesi',
  'Ankara Müzik ve Güzel Sanatlar Üniversitesi',
  'Ankara Sosyal Bilimler Üniversitesi',
  'Ankara Üniversitesi',
  'Ankara Yıldırım Beyazıt Üniversitesi',
  'Antalya Akev Üniversitesi',
  'Antalya Bilim Üniversitesi',
  'Ardahan Üniversitesi',
  'Artvin Çoruh Üniversitesi',
  'Atatürk Üniversitesi',
  'Atılım Üniversitesi',
  'Avrasya Üniversitesi',
  'Aydın Adnan Menderes Üniversitesi',
  'Bahçeşehir Üniversitesi',
  'Balıkesir Üniversitesi',
  'Bandırma Onyedi Eylül Üniversitesi',
  'Bartın Üniversitesi',
  'Başkent Üniversitesi',
  'Batman Üniversitesi',
  'Bayburt Üniversitesi',
  'Beykent Üniversitesi',
  'Beykoz Üniversitesi',
  'Bezmialem Vakıf Üniversitesi',
  'Bilecik Şeyh Edebali Üniversitesi',
  'Bingöl Üniversitesi',
  'Biruni Üniversitesi',
  'Bitlis Eren Üniversitesi',
  'Boğaziçi Üniversitesi',
  'Bolu Abant İzzet Baysal Üniversitesi',
  'Bursa Teknik Üniversitesi',
  'Bursa Uludağ Üniversitesi',
  'Çanakkale Onsekiz Mart Üniversitesi',
  'Çankaya Üniversitesi',
  'Çankırı Karatekin Üniversitesi',
  'Çukurova Üniversitesi',
  'Dicle Üniversitesi',
  'Doğuş Üniversitesi',
  'Dokuz Eylül Üniversitesi',
  'Düzce Üniversitesi',
  'Ege Üniversitesi',
  'Erciyes Üniversitesi',
  'Erzincan Binali Yıldırım Üniversitesi',
  'Erzurum Teknik Üniversitesi',
  'Eskişehir Osmangazi Üniversitesi',
  'Eskişehir Teknik Üniversitesi',
  'Fenerbahçe Üniversitesi',
  'Fırat Üniversitesi',
  'Galatasaray Üniversitesi',
  'Gazi Üniversitesi',
  'Gaziantep İslam Bilim ve Teknoloji Üniversitesi',
  'Gaziantep Üniversitesi',
  'Gaziosmanpaşa Üniversitesi',
  'Gebze Teknik Üniversitesi',
  'Giresun Üniversitesi',
  'Gümüşhane Üniversitesi',
  'Hacettepe Üniversitesi',
  'Hakkari Üniversitesi',
  'Haliç Üniversitesi',
  'Harran Üniversitesi',
  'Hasan Kalyoncu Üniversitesi',
  'Hatay Mustafa Kemal Üniversitesi',
  'Hitit Üniversitesi',
  'Iğdır Üniversitesi',
  'Isparta Uygulamalı Bilimler Üniversitesi',
  'İbn Haldun Üniversitesi',
  'İhsan Doğramacı Bilkent Üniversitesi',
  'İnönü Üniversitesi',
  'İskenderun Teknik Üniversitesi',
  'İstanbul 29 Mayıs Üniversitesi',
  'İstanbul Arel Üniversitesi',
  'İstanbul Atlas Üniversitesi',
  'İstanbul Aydın Üniversitesi',
  'İstanbul Ayvansaray Üniversitesi',
  'İstanbul Bilgi Üniversitesi',
  'İstanbul Bilim Üniversitesi',
  'İstanbul Esenyurt Üniversitesi',
  'İstanbul Galata Üniversitesi',
  'İstanbul Gedik Üniversitesi',
  'İstanbul Gelişim Üniversitesi',
  'İstanbul Kent Üniversitesi',
  'İstanbul Kültür Üniversitesi',
  'İstanbul Medeniyet Üniversitesi',
  'İstanbul Medipol Üniversitesi',
  'İstanbul Okan Üniversitesi',
  'İstanbul Rumeli Üniversitesi',
  'İstanbul Sabahattin Zaim Üniversitesi',
  'İstanbul Sağlık ve Teknoloji Üniversitesi',
  'İstanbul Teknik Üniversitesi',
  'İstanbul Ticaret Üniversitesi',
  'İstanbul Üniversitesi',
  'İstanbul Yeni Yüzyıl Üniversitesi',
  'İstinye Üniversitesi',
  'İzmir Bakırçay Üniversitesi',
  'İzmir Demokrasi Üniversitesi',
  'İzmir Ekonomi Üniversitesi',
  'İzmir Katip Çelebi Üniversitesi',
  'İzmir Tınaztepe Üniversitesi',
  'İzmir Yüksek Teknoloji Enstitüsü',
  'Kadir Has Üniversitesi',
  'Kafkas Üniversitesi',
  'Kahramanmaraş İstiklal Üniversitesi',
  'Kahramanmaraş Sütçü İmam Üniversitesi',
  'Kapadokya Üniversitesi',
  'Karabük Üniversitesi',
  'Karadeniz Teknik Üniversitesi',
  'Karamanoğlu Mehmetbey Üniversitesi',
  'Kastamonu Üniversitesi',
  'Kırıkkale Üniversitesi',
  'Kırklareli Üniversitesi',
  'Kırşehir Ahi Evran Üniversitesi',
  'Kilis 7 Aralık Üniversitesi',
  'Kocaeli Sağlık ve Teknoloji Üniversitesi',
  'Kocaeli Üniversitesi',
  'Konya Gıda ve Tarım Üniversitesi',
  'Konya Teknik Üniversitesi',
  'KTO Karatay Üniversitesi',
  'Malatya Turgut Özal Üniversitesi',
  'Maltepe Üniversitesi',
  'Manisa Celal Bayar Üniversitesi',
  'Mardin Artuklu Üniversitesi',
  'Marmara Üniversitesi',
  'Mersin Üniversitesi',
  'Mimar Sinan Güzel Sanatlar Üniversitesi',
  'Muğla Sıtkı Koçman Üniversitesi',
  'Munzur Üniversitesi',
  'Muş Alparslan Üniversitesi',
  'Nevşehir Hacı Bektaş Veli Üniversitesi',
  'Niğde Ömer Halisdemir Üniversitesi',
  'Nişantaşı Üniversitesi',
  'Ondokuz Mayıs Üniversitesi',
  'Ordu Üniversitesi',
  'Orta Doğu Teknik Üniversitesi',
  'Osmaniye Korkut Ata Üniversitesi',
  'Ostim Teknik Üniversitesi',
  'Pamukkale Üniversitesi',
  'Piri Reis Üniversitesi',
  'Recep Tayyip Erdoğan Üniversitesi',
  'Sabancı Üniversitesi',
  'Sakarya Uygulamalı Bilimler Üniversitesi',
  'Sakarya Üniversitesi',
  'Samsun Üniversitesi',
  'Sanko Üniversitesi',
  'Selçuk Üniversitesi',
  'Siirt Üniversitesi',
  'Sinop Üniversitesi',
  'Sivas Bilim ve Teknoloji Üniversitesi',
  'Sivas Cumhuriyet Üniversitesi',
  'Süleyman Demirel Üniversitesi',
  'Şırnak Üniversitesi',
  'TED Üniversitesi',
  'Tekirdağ Namık Kemal Üniversitesi',
  'Tokat Gaziosmanpaşa Üniversitesi',
  'Toros Üniversitesi',
  'Trakya Üniversitesi',
  'Trabzon Üniversitesi',
  'Tunceli Munzur Üniversitesi',
  'Türk-Alman Üniversitesi',
  'Türk Hava Kurumu Üniversitesi',
  'Ufuk Üniversitesi',
  'Uşak Üniversitesi',
  'Üsküdar Üniversitesi',
  'Van Yüzüncü Yıl Üniversitesi',
  'Yalova Üniversitesi',
  'Yaşar Üniversitesi',
  'Yeditepe Üniversitesi',
  'Yıldız Teknik Üniversitesi',
  'Yozgat Bozok Üniversitesi',
  'Zonguldak Bülent Ecevit Üniversitesi',
  'Diğer',
];
